rules:
  hand_enabled: true
  events_enabled: true
  micro_bribe_once_per_turn: true
  ammo_max_bonus: 2
  cascade_enabled: true
  cascade_reward: 3
  cascade_max_triggers: 2

# Лимит руки по умолчанию (может быть увеличен до 7/8 и выше эффектами)
hand_limit: 6

# Полка: без ограничения размера. Если вся закрытая колода ушла на полку,
# полка тасуется и выкладывается лицом вниз (поведение зададим логикой движка позже).
# shelf_unlimited зарезервирован на будущее, сейчас носит справочный характер.
shelf_unlimited: true

# Стартовые карты (не в колоде): по одному Боссу на игрока (ID из config/cards.csv)
starters:
  P1:
    - boss_gangster
  P2:
    - boss_authority

# Карты загружаются исключительно из config/cards.csv
# Данный раздел удален для предотвращения дублирования источников данных
