rules:
  hand_enabled: true
  events_enabled: true
  micro_bribe_once_per_turn: true
  ammo_max_bonus: 2
  cascade_enabled: true
  cascade_reward: 3
  cascade_max_triggers: 2

# Лимит руки по умолчанию (может быть увеличен до 7/8 и выше эффектами)
hand_limit: 6

# Полка: без ограничения размера. Если вся закрытая колода ушла на полку,
# полка тасуется и выкладывается лицом вниз (поведение зададим логикой движка позже).
# shelf_unlimited зарезервирован на будущее, сейчас носит справочный характер.
shelf_unlimited: true

# Стартовые карты (не в колоде): по одному Боссу на игрока
starters:
  P1:
    - id: boss_p1
      name: Босс П1
      type: boss
      faction: gangsters
      hp: 12
      atk: 2
      d: 1
      abl:
        authority: 1
      notes: "Авторитет +1: союзные карты получают +1 к квоте защиты (D) при найме Братков"
  P2:
    - id: boss_p2
      name: Босс П2
      type: boss
      faction: government
      hp: 12
      atk: 2
      d: 1
      abl:
        authority: 1
      notes: "Авторитет +1: союзные карты получают +1 к квоте защиты (D) при найме Братков"

# Карты в общей колоде (кладовая)
cards:
  - id: thug_1
    name: Головорез
    type: common
    faction: gangsters
    hp: 4
    atk: 2
    d: 1
    abl: 0
    notes: "Базовый нападающий: стабильные 2 урона, строит оборону со скоростью D=1"
    in_deck: true
  - id: guard_1
    name: Страж
    type: common
    faction: government
    hp: 5
    atk: 1
    d: 2
    abl: 0
    notes: "Опорный защитник: D=2 ускоряет найм Братков"
    in_deck: true
  - id: fixer_1
    name: Решала
    type: common
    faction: mercenaries
    hp: 3
    atk: 1
    d: 1
    abl: 2
    notes: "Поддержка: abl=2 — числовой рейтинг; на текущей версии без встроенного эффекта"
    in_deck: true
  - id: sentinel_extra
    name: Страж-экстра
    type: common
    faction: government
    hp: 5
    atk: 1
    d: 1
    abl:
      extra_defense: 1
    notes: "extra_defense +1: повышает квоту защиты этой карты (D) на +1"
    in_deck: true
  - id: event_plus_cash
    name: Сейф вскрыт
    type: event
    meta: {kind: positive}
    notes: "Сразу: получить деньги по эффекту события"
    in_deck: true
  - id: event_minus_raid
    name: Рейд
    type: event
    meta: {kind: negative}
    notes: "Сразу: потеря части денег по эффекту события"
    in_deck: true
  # --- Минимальная тестовая колода: дополнительные персонажи ---
  - id: bruiser_1
    name: Амбал
    type: common
    faction: mercenaries
    hp: 4
    atk: 3
    d: 1
    abl: 0
    notes: "Атакующий: 3 урона, но медленно строит защиту (D=1)"
    in_deck: true
  - id: brawler_1
    name: Забияка
    type: common
    faction: gangsters
    hp: 3
    atk: 3
    d: 1
    abl: 0
    notes: "Стеклянная пушка: высокий урон, низкий запас HP"
    in_deck: true
  - id: raider_1
    name: Налётчик
    type: common
    faction: gangsters
    hp: 4
    atk: 2
    d: 1
    abl: 0
    notes: "Гибкий нападающий: сбалансированные HP/урон"
    in_deck: true
  - id: cutthroat_1
    name: Головорез-ветеран
    type: common
    faction: gangsters
    hp: 5
    atk: 3
    d: 1
    abl: 0
    notes: "Усиленная версия атакера: выше HP и урон"
    in_deck: false
  - id: enforcer_1
    name: Силовик
    type: common
    faction: government
    hp: 5
    atk: 2
    d: 2
    abl: 0
    notes: "Силовая поддержка защитной линии: D=2 и средний урон"
    in_deck: false
  - id: shield_1
    name: Щитоносец
    type: common
    faction: government
    hp: 6
    atk: 0
    d: 3
    abl: 0
    notes: "Танк: максимальный темп защиты (D=3), урона не наносит"
    in_deck: true
  - id: sentinel_2
    name: Страж-2
    type: common
    faction: government
    hp: 5
    atk: 1
    d: 2
    abl: 0
    notes: "Надёжный защитник второго ряда: D=2"
    in_deck: true
  - id: thief_1
    name: Вор
    type: common
    faction: gangsters
    hp: 3
    atk: 0
    d: 1
    abl:
      on_enter:
        steal: 2
    notes: "При входе на стол: украсть 2💰 у оппонента, если есть (on-enter)"
    in_deck: true
  - id: financier_1
    name: Финансист
    type: common
    faction: government
    hp: 3
    atk: 1
    d: 1
    abl:
      on_enter:
        gain: 1
    notes: "При входе на стол: получить 1💰 (on-enter: gain)"
    in_deck: true
  - id: patron_1
    name: Патроном
    type: common
    faction: gangsters
    hp: 4
    atk: 1
    d: 1
    abl:
      on_enter:
        gain: 1
    notes: "При входе на стол: получить 1💰 (on-enter: gain)"
    in_deck: true
  - id: broker_1
    name: Брокер
    type: common
    faction: mercenaries
    hp: 3
    atk: 1
    d: 1
    abl: 3
    notes: "Поддержка экономики: abl=3 — числовой рейтинг; без встроенного эффекта"
    in_deck: false
  - id: lookout_1
    name: Дозорный
    type: common
    faction: government
    hp: 4
    atk: 1
    d: 2
    abl: 1
    notes: "Наблюдатель линии: D=2, низкий урон"
    in_deck: false
  # --- События (минимум 6, две реализованы в движке, остальные как заглушки logging-only) ---
  - id: event_audit
    name: Аудит
    type: event
    meta: {kind: negative}
    notes: "Сразу: штраф по экономике"
    in_deck: true
  - id: event_supply_snafu
    name: Срыв поставки
    type: event
    meta: {kind: negative}
    notes: "Сразу: временные ограничения на тактики хода"
    in_deck: true
  - id: event_cash2
    name: Премия
    type: event
    meta: {kind: positive}
    notes: "Сразу: получить дополнительную сумму денег"
    in_deck: true
  - id: event_recruit
    name: Вербовка
    type: event
    meta: {kind: positive}
    notes: "Сразу: манипуляция с Братками/жетонами в вашу пользу"
    in_deck: true
